### ISSUE TITLE
Minimal install README.md

### ISSUE THREAD

**Issue by ghost** [gobolinux/BuildLiveCD#1]
Hello,

Would it be possible to add a minimal README.md as starter file? That is, how to get the gobolinux LIVE CD built? Also would this apply to a Live DVD as well?

Perhaps a short README.md could mention this. Anyway thanks for reading!

**Comment by lucasvr** [comment]
Thanks for the suggestion, I'm about to write a small doc for this package. Please note that this package alone does not do much. The main tool that invokes BuildLiveCD and other utilities related to the LiveCD is GoboALFS (which does have a starter README.md file).

**Comment by waldyrious** [comment]
For future reference, the commit that closed this issue was de3274d.
